// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Category struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	VoteType    string        `json:"vote_type"`
	Status      string        `json:"status"`
	ShowResults string        `json:"show_results"`
	MaxRank     sql.NullInt64 `json:"max_rank"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Option struct {
	ID         int64         `json:"id"`
	CategoryID int64         `json:"category_id"`
	Name       string        `json:"name"`
	SortOrder  sql.NullInt64 `json:"sort_order"`
}

type Vote struct {
	ID         int64        `json:"id"`
	CategoryID int64        `json:"category_id"`
	Nickname   string       `json:"nickname"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type VoteSelection struct {
	ID       int64         `json:"id"`
	VoteID   int64         `json:"vote_id"`
	OptionID int64         `json:"option_id"`
	Rank     sql.NullInt64 `json:"rank"`
}
