// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getCategory = `-- name: GetCategory :one

SELECT id, name, vote_type, status, show_results, max_rank, created_at FROM categories WHERE id = ?
`

// Queries for sqlc code generation
func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VoteType,
		&i.Status,
		&i.ShowResults,
		&i.MaxRank,
		&i.CreatedAt,
	)
	return i, err
}
